# -*- coding: utf-8 -*-
"""ExternalExam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvgbwy-qcwv1LamIgpaj6xto7RRFqRyl
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris

iris=load_iris()

x=iris.data
y=iris.target

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=30)

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.tree import plot_tree

dt=DecisionTreeClassifier()

dt.fit(x_train,y_train)

pred=dt.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print("Accuracy",accuracy_score(y_test,pred))
print("Classification Report",classification_report(y_test,pred))

plt.figure(figsize=(15,15))
tree.plot_tree(dt,filled=True,class_names=iris.target_names,feature_names=iris.feature_names)
plt.show()

